version: "3.7"

services: 
  database:
    image: postgres
    container_name: database_promovi
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=promovi
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379

    
volumes:
  pgdata:
    driver: local